export const errorMessages = [
    "Oh, fantastic. The URL you provided is as valid as my New Year's resolutions. How about heading back to the main page and giving it another try?",
    "Oh, brilliant. The URL you provided is as reliable as my Wi-Fi signal. Maybe try again?",
    "Well, isn't this wonderful. The URL you provided is about as functional as my old flip phone. Care to try again?",
    "Oh, joy. The URL you entered is as useful as a solar-powered flashlight. Why not give it another shot?",
    "Splendid. The URL you provided is as accurate as my sense of direction. How about trying again?",
    "Oh, great. The URL you provided is as reliable as my memory. Maybe head back to the main page and try again?",
    "Oh, lovely. The URL you entered is as effective as my gym membership. Try again, perhaps?",
    "Fantastic. The URL you provided is as valid as my excuses for being late. Care to try again?",
    "Oh, marvelous. The URL you entered is as believable as my poker face. How about trying again?",
    "Oh, delightful. The URL you provided is as useful as a chocolate teapot. Why not head back and give it another go?",
    "Oh, splendid. The URL you provided is as functional as my holiday plans. Maybe try again?",
    "Oh, brilliant. The URL you entered is as valid as my chances of winning the lottery. How about trying again?",
    "Oh, fantastic. The URL you provided is as effective as my attempts at cooking. Care to try again?",
    "Oh, joy. The URL you entered is as reliable as my alarm clock. Why not give it another shot?",
    "Oh, lovely. The URL you provided is as accurate as my weather predictions. Maybe try again?",
    "Oh, marvelous. The URL you entered is as functional as my last DIY project. How about trying again?",
    "Oh, splendid. The URL you provided is as believable as my dance moves. Care to try again?",
    "Oh, brilliant. The URL you entered is as useful as a screen door on a submarine. Maybe try again?",
    "Oh, fantastic. The URL you provided is as reliable as my cat's obedience. Why not head back and give it another go?",
    "Oh, joy. The URL you entered is as valid as my diet plan. How about trying again?",
    "Oh, lovely. The URL you provided is as effective as my old typewriter. Care to try again?",
    "Oh, marvelous. The URL you entered is as useful as a one-legged man in a butt-kicking contest. Maybe try again?",
    "Oh, splendid. The URL you provided is as believable as my fishing stories. How about trying again?",
    "Oh, brilliant. The URL you entered is as valid as my singing voice. Why not give it another shot?",
    "Oh, fantastic. The URL you provided is as reliable as my computer when I need it most. Maybe try again?",
    "Oh, joy. The URL you entered is as effective as my attempts at growing a beard. Care to try again?",
    "Oh, lovely. The URL you provided is as accurate as my aim in video games. How about trying again?",
    "Oh, marvelous. The URL you entered is as functional as my car when it's cold. Maybe try again?",
    "Oh, splendid. The URL you provided is as believable as my claims of being a morning person. Why not head back and give it another go?",
    "Oh, brilliant. The URL you entered is as useful as an ashtray on a motorcycle. Care to try again?",
    "Oh, fantastic. The URL you provided is as reliable as my friend's punctuality. How about trying again?",
    "Oh, joy. The URL you entered is as valid as my dog's promises. Maybe try again?",
    "Oh, lovely. The URL you provided is as effective as my attempts at parallel parking. Why not give it another shot?",
    "Oh, marvelous. The URL you entered is as useful as a waterproof towel. How about trying again?",
    "Oh, splendid. The URL you provided is as believable as my sleep schedule. Care to try again?",
    "Oh, brilliant. The URL you entered is as valid as my New Year's resolutions. Maybe try again?",
    "Oh, fantastic. The URL you provided is as reliable as my Wi-Fi signal. How about trying again?",
    "Oh, joy. The URL you entered is as useful as a screen door on a spaceship. Care to try again?",
    "Oh, lovely. The URL you provided is as accurate as my directions. Why not give it another shot?",
    "Oh, marvelous. The URL you entered is as functional as my Monday mornings. How about trying again?",
    "Oh, splendid. The URL you provided is as believable as my magic tricks. Maybe try again?",
    "Oh, brilliant. The URL you entered is as valid as my old VCR. How about trying again?",
    "Oh, fantastic. The URL you provided is as effective as my attempts at eating healthy. Care to try again?",
    "Oh, joy. The URL you entered is as reliable as my pet goldfish's memory. Why not give it another shot?",
    "Oh, lovely. The URL you provided is as accurate as my horoscopes. Maybe try again?",
    "Oh, marvelous. The URL you entered is as functional as my old flip phone. How about trying again?",
    "Oh, splendid. The URL you provided is as believable as my excuses for not working out. Care to try again?",
    "Oh, brilliant. The URL you entered is as useful as a chocolate fireguard. Maybe try again?",
    "Oh, fantastic. The URL you provided is as reliable as my old car. How about trying again?",
    "Oh, joy. The URL you entered is as valid as my promises to diet. Why not give it another shot?",
    "Oh, lovely. The URL you provided is as effective as my attempts at being on time. Maybe try again?",
    "Oh, marvelous. The URL you entered is as useful as a solar-powered flashlight at night. How about trying again?",
    "Oh, splendid. The URL you provided is as believable as my sleepwalking stories. Care to try again?",
    "Oh, brilliant. The URL you entered is as valid as my productivity after lunch. Maybe try again?",
    "Oh, fantastic. The URL you provided is as reliable as my cat's promises. How about trying again?",
    "Oh, joy. The URL you entered is as useful as a comb to a bald man. Why not give it another shot?",
    "Oh, lovely. The URL you provided is as accurate as my watch after a swim. Maybe try again?",
    "Oh, marvelous. The URL you entered is as functional as my sense of humor at 6 AM. How about trying again?",
    "Oh, splendid. The URL you provided is as believable as my online dating profile. Care to try again?",
    "Oh, brilliant. The URL you entered is as useful as an inflatable dartboard. Maybe try again?",
    "Oh, fantastic. The URL you provided is as reliable as my old laptop's battery. How about trying again?",
    "Oh, joy. The URL you entered is as valid as my pet's promises to behave. Why not give it another shot?",
    "Oh, lovely. The URL you provided is as effective as my attempts at fixing things. Maybe try again?",
    "Oh, marvelous. The URL you entered is as useful as a glass hammer. How about trying again?",
    "Oh, splendid. The URL you provided is as believable as my Monday morning cheerfulness. Care to try again?",
    "Oh, brilliant. The URL you entered is as valid as my attempts at being organized. Maybe try again?",
    "Oh, fantastic. The URL you provided is as reliable as my sense of direction in a maze. How about trying again?",
    "Oh, joy. The URL you entered is as useful as a white crayon. Why not give it another shot?",
    "Oh, lovely. The URL you provided is as accurate as my guesswork on trivia night. Maybe try again?",
    "Oh, marvelous. The URL you entered is as functional as my phone after dropping it in water. How about trying again?",
    "Oh, splendid. The URL you provided is as believable as my claims of having a green thumb. Care to try again?",
    "Oh, brilliant. The URL you entered is as useful as an ejector seat in a helicopter. Maybe try again?",
    "Oh, fantastic. The URL you provided is as reliable as my ability to resist chocolate. How about trying again?",
    "Oh, joy. The URL you entered is as valid as my old TV antenna. Why not give it another shot?",
    "Oh, lovely. The URL you provided is as effective as my attempts at fixing my own plumbing. Maybe try again?",
    "Oh, marvelous. The URL you entered is as useful as a screen door on a submarine. How about trying again?",
    "Oh, splendid. The URL you provided is as believable as my pet's promise to stay off the couch. Care to try again?",
    "Oh, brilliant. The URL you entered is as valid as my chances of becoming an astronaut. Maybe try again?",
    "Oh, fantastic. The URL you provided is as reliable as my attempts at DIY. How about trying again?",
    "Oh, joy. The URL you entered is as useful as a snowblower in the Sahara. Why not give it another shot?",
    "Oh, lovely. The URL you provided is as accurate as my aim with a rubber band. Maybe try again?",
    "Oh, marvelous. The URL you entered is as functional as my willpower near a cookie jar. How about trying again?",
    "Oh, splendid. The URL you provided is as believable as my claims of being tech-savvy. Care to try again?",
    "Oh, brilliant. The URL you entered is as useful as a waterproof teabag. Maybe try again?",
    "Oh, fantastic. The URL you provided is as reliable as my car's gas gauge. How about trying again?",
    "Oh, joy. The URL you entered is as valid as my New Year's gym membership. Why not give it another shot?",
    "Oh, lovely. The URL you provided is as effective as my attempts at gardening. Maybe try again?",
    "Oh, marvelous. The URL you entered is as useful as a paper umbrella in a hurricane. How about trying again?",
    "Oh, splendid. The URL you provided is as believable as my dog's ability to talk. Care to try again?",
    "Oh, brilliant. The URL you entered is as valid as my claims of understanding quantum physics. Maybe try again?",
    "Oh, splendid. The URL you provided is as effective as my self-control in a candy store. Maybe try again?",
    "Oh, fantastic. The URL you provided is as reliable as my ability to follow a diet. How about heading back to the main page and giving it another try?",
    "Oh, marvelous. The URL you provided is as useful as a chocolate teapot in a heatwave. Care to try again?",
    "Oh, brilliant. The URL you entered is as functional as my phone after a swim. Maybe try again?",
    "Oh, joy. The URL you provided is as valid as my promises to go to the gym. How about trying again?",
    "Oh, lovely. The URL you provided is as accurate as my watch after I dropped it. Maybe head back to the main page and try again?",
    "Oh, fantastic. The URL you entered is as reliable as my willpower in a bakery. How about trying again?",
    "Oh, marvelous. The URL you provided is as useful as a waterproof sponge. Care to try again?",
    "Oh, splendid. The URL you entered is as believable as my excuses for missing deadlines. Maybe try again?",
    "Oh, joy. The URL you provided is as effective as my attempts at staying organized. How about trying again?",
    "Oh, lovely. The URL you entered is as reliable as my self-discipline during the holidays. Why not give it another shot?",
    "Oh, fantastic. The URL you provided is as accurate as my guesses on a math test. Care to try again?",
    "Oh, marvelous. The URL you entered is as useful as an inflatable dartboard. Maybe try again?",
    "Oh, brilliant. The URL you provided is as valid as my cat's promises to stop knocking things over. How about heading back and giving it another go?",
    "Oh, splendid. The URL you entered is as effective as my attempts at learning a new language. Care to try again?",
    "Oh, joy. The URL you provided is as reliable as my friend's word to call back. How about trying again?",
    "Oh, lovely. The URL you entered is as useful as a solar-powered flashlight in a blackout. Maybe head back to the main page and try again?",
    "Oh, fantastic. The URL you provided is as believable as my claims of being on time. How about trying again?",
    "Oh, marvelous. The URL you entered is as reliable as my dog's promises to stay out of trouble. Care to try again?",
    "Oh, splendid. The URL you provided is as useful as a screen door on a helicopter. Maybe try again?",
    "Oh, excellent. The URL you provided is like a fine wine – if by 'fine' you mean 'spoiled' and by 'wine' you mean 'vinegar'. How about you head back and try again with an actual working URL?",
    "Oh, fantastic. The URL you entered is as sharp as a marble. Maybe give it another go, genius?",
    "Well, isn't this just delightful. The URL you provided is as coherent as a drunk text at 3 AM. Perhaps try something a bit more logical?",
    "Oh, joy. The URL you provided is as functional as a chocolate fireman. Why not give it another shot and impress us with your URL-choosing prowess?",
    "Oh, lovely. The URL you entered is as promising as my chances of winning an Olympic gold medal in procrastination. How about trying again?",
    "Oh, splendid. The URL you provided is as accurate as a politician's promise. Maybe head back to the main page and try with a URL that actually exists?",
    "Oh, brilliant. The URL you entered is as effective as a waterproof sponge. Maybe try again and prove you're capable of basic tasks?",
    "Oh, fantastic. The URL you provided is as reliable as a paper umbrella in a hurricane. How about heading back and giving it another try, Einstein?"
  ];
  